# Generated by Django 4.2.4 on 2023-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store_custo_last_na_c00a35_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customeers',
        ),
    ]
